import type { PressReaderCommonConfig } from "./types";

export const commonConfigKeys: (keyof PressReaderCommonConfig)[] = [
  "colorBrand",
  "colorBrandDark",
  "colorBackground",
  "colorBackgroundDark",
  "brandGradientStartColor",
  "brandGradientEndColor",
  "onboardingEnabled",
  "sdkExitButtonText",
  "supportEmailAddress",
  "newsfeedApi",
  "articleCommentsEnabled",
  "articleVotesEnabled",
  "isPopupArticleViewAllowed",
  "readerExternalLinksEnabled",
  "localServerUrl",
  "showCustomerSupport",
  "supportPhoneNumber",
  "termsOfUseUrl",
  "privacyPolicyUrl",
  "registrationUrl",
  "translateEnabled",
  "showRegistration",
  "facebookUrl",
  "instagramUrl",
  "twitterUrl",
  "youtubeUrl",
];
